spring.application.name=bunny-org-app

spring.datasource.url=jdbc:postgresql://localhost:5432/zecevi
spring.datasource.username=postgres
spring.datasource.password=super
spring.jpa.hibernate.ddl-auto=update

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

server.port=8081

