spring.application.name=Ad_agency_1
server.port=8083
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest


queue.exchange=ads
queue.name=ads-agency-web-2

# Interval pollinga (ms)
poll.interval.ms=5000